### ISSUE TITLE
survey.routines.inquire doesn't like wrong case

### ISSUE THREAD

**Issue by jmurrayufo** [Exahilosys/survey#17]
Running on `survey==4.4.0` under `Python 3.11.4`, execute the following code:

```
import survey

survey.routines.inquire("Will you error?")
```

When prompted, press shift and N or shift and Y. The resulting error follows

```
? Will you error?(y/n) Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 365, in invoke
    widget.invoke(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 183, in invoke
    self._invoke(event, info)
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 159, in _invoke
    self._handle.invoke(event, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/survey/_handle.py", line 104, in invoke
    self._dispatch(EventType.leave, event, *args)
  File "/usr/local/lib/python3.11/site-packages/survey/_handle.py", line 80, in _dispatch
    self._callback(event, *args)
  File "/usr/local/lib/python3.11/site-packages/survey/_helpers.py", line 197, in function
    function(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/survey/_helpers.py", line 197, in function
    function(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/survey/_handle.py", line 102, in invoke
    control.function(*self._args, *args)
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 765, in _control_insert_leave
    raise _core.Terminate()
survey._core._handle.Terminate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/scripts/bug_example.py", line 3, in <module>
    survey.routines.inquire("Will you error?")
  File "/usr/local/lib/python3.11/site-packages/survey/_theme.py", line 75, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_routines.py", line 259, in _inquire
    value = _widgets.start(
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 385, in _start
    _system.console.start(sketch, invoke)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_console.py", line 91, in start
    self._start(sketch, invoke)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_console.py", line 71, in _start
    self._handle.start(callback)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_handle.py", line 57, in start
    self._start(invoke)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_handle.py", line 41, in _start
    source.listen()
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_source.py", line 189, in listen
    self._listen()
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_source.py", line 181, in _listen
    self._advance()
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_source.py", line 175, in _advance
    self._process(info)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_source.py", line 168, in _process
    self._callback(name, info)
  File "/usr/local/lib/python3.11/site-packages/survey/_core/_console.py", line 64, in callback
    invoke(name, info)
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 367, in invoke
    result = widget.resolve()
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 137, in resolve
    result = self._resolve()
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/survey/_widgets.py", line 838, in _resolve
    value = self._options[field]
            ~~~~~~~~~~~~~^^^^^^^
KeyError: 'Y'
```

**Comment by jmurrayufo** [comment]
Thanks!
