### ISSUE TITLE
control character issues

### ISSUE THREAD

**Issue by fawaf** [Exahilosys/survey#26]
when a script is run and terminal controls are shown, it seems to hard freeze the terminal and no more input is accepted. happy to provide more debugging info, but no idea how to do that.

below is what the terminal looks like when this happens
```
% /tmp/test
? select: ^[[48;15R
```

**Comment by Exahilosys** [comment]
Hello! Thank you for reporting this. It seems like the terminal isn't getting set up right to accept ansi sequences. Could you please provide a snippet to reproduce this? What OS are you on?

**Comment by fawaf** [comment]
i'm using wsl on windows 11 when this occurred.

```#!/usr/bin/env python3

import survey
import uuid
import random

stuff = [str(uuid.uuid4()) for i in range(1, random.randint(1, 23))]

idx = survey.routines.select(
    "select: ",
    options=stuff,
    focus_mark="> ",
    evade_color=survey.colors.basic("yellow"),
)
print(idx)
```

**Comment by Exahilosys** [comment]
That's curious, I cannot replicate this with WSL on Windows 10. It seems like the the terminal is properly heading to the command of returning the cursor location, but for some reason it is echoing it back instead of passing it to the input buffer. This would only happen if the [mode setting for echoing](https://github.com/Exahilosys/survey/blob/main/survey/_core/_io_os_posix.py#L31) did not happen successfully. 

Unfortunately with no way to reproduce this and without knowing the state of the terminal mode at the time this occurs, there is no way to proceed. If you could somehow print `survey.system.io._i_mode` when you encounter this again, it may be a start give some very valuable information.

**Comment by fawaf** [comment]
Hmm, it gives an error:
```
AttributeError: 'IO' object has no attribute '_i_mode'
```

**Comment by Exahilosys** [comment]
Ah my bad! The mode does not get set unless IO is used somehow, a safeguard should do the trick:

```py
getattr(survey.system.io, '_i_mode', None)
```

**Comment by fawaf** [comment]
Got the issue once, but it wasn't able to print anything since the terminal froze. I did get a stacktrace after ctrl-c though
```
a396-4422-93f2-a34a3a87ba9d
  4c3c4a17-7c03-40d7-b493-fad4a8d81ca9
  09d8b049-25ec-4670-9d4b-db1fb6e018d7
                                                                                                         ^[[48;106RTraceback (most recent call last):
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 72, in _read_code
    code = self._code_buffer[index]
           ~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 116, in function
    rune = memo.pop(0)
           ^^^^^^^^^^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waf/./test", line 10, in <module>
    idx = survey.routines.select(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_theme.py", line 75, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_routines.py", line 355, in _select
    result = _widgets.start(
             ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_widgets.py", line 392, in _start
    _system.console.start(sketch, invoke)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_console.py", line 91, in start
    self._start(sketch, invoke)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_console.py", line 71, in _start
    self._handle.start(callback)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_handle.py", line 56, in start
    self._start(invoke)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_handle.py", line 40, in _start
    source.listen()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_source.py", line 152, in listen
    self._listen()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_source.py", line 144, in _listen
    self._advance()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_source.py", line 139, in _advance
    self._process(info)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_source.py", line 132, in _process
    self._callback(name, info)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_console.py", line 67, in callback
    print(True)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_console.py", line 60, in print
    self._screen.print(sketch, re)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_screen.py", line 70, in print
    self._print(sketch, re, clean = clean, learn = learn)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_screen.py", line 46, in _print
    self._render.draw(*info, **kwargs)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_render.py", line 247, in draw
    self._draw(learn, clean, lines, point)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_render.py", line 190, in _draw
    max_y, max_x = self._cursor.measure()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_cursor.py", line 353, in measure
    point = self._measure()
            ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_cursor.py", line 337, in _measure
    point = self._locate()
            ^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_cursor.py", line 309, in _locate
    code = self._intel.read(check = check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 93, in read
    return self._read(check)
           ^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 87, in _read
    code = self._read_code(check)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 74, in _read_code
    self._fill_code()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 57, in _fill_code
    code = _ansi.parse(self._read_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 161, in parse
    return _parse(get)
           ^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 135, in _parse
    rune = get()
           ^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 118, in function
    text = get()
           ^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 43, in _read_text
    self._fill_text()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 34, in _fill_text
    text = self._io.recv()
           ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io_os.py", line 43, in recv
    text = self._recv()
           ^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io.py", line 71, in _recv
    text_raw = super()._recv()
               ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io_os.py", line 119, in _recv
    text = self._i.read1()
           ^^^^^^^^^^^^^^^
KeyboardInterrupt

waf@la
```

**Comment by Exahilosys** [comment]
@fawaf I'm confident this should fix the issue, but I am not closing this yet, let me know if the issue persists.

**Comment by fawaf** [comment]
Just tested it out with v5.2.3 and it errored still. Full output below
```
waf@lara. | dir: ~
% ./test                                                          [131] 2024-02-25 17:40:14 PST (2024.08)
None
^[[46;1RTraceback (most recent call last):
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 77, in _read_code
    code = self._code_buffer[index]
           ~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 116, in function
    rune = memo.pop(0)
           ^^^^^^^^^^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waf/./test", line 10, in <module>
    idx = survey.routines.select(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_theme.py", line 75, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_routines.py", line 355, in _select
    result = _widgets.start(
             ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_widgets.py", line 346, in _start
    _system.screen.print(show_get, False, learn = False)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_screen.py", line 73, in print
    self._print(sketch, re, clean = clean, learn = learn)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_screen.py", line 49, in _print
    self._render.draw(*info, **kwargs)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_render.py", line 240, in draw
    self._draw(learn, clean, lines, point)
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_render.py", line 182, in _draw
    cur_y, cur_x = self._cursor.locate()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_cursor.py", line 333, in locate
    point = self._locate()
            ^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_cursor.py", line 318, in _locate
    code = self._intel.read(check = check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 98, in read
    return self._read(check)
           ^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 92, in _read
    code = self._read_code(check)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_helpers.py", line 35, in wrapper
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 79, in _read_code
    self._fill_code()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 62, in _fill_code
    code = _ansi.parse(self._read_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 161, in parse
    return _parse(get)
           ^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 135, in _parse
    rune = get()
           ^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_ansi.py", line 118, in function
    text = get()
           ^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 48, in _read_text
    self._fill_text()
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_intel.py", line 39, in _fill_text
    text = self._io.recv()
           ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io_os.py", line 43, in recv
    text = self._recv()
           ^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io.py", line 71, in _recv
    text_raw = super()._recv()
               ^^^^^^^^^^^^^^^
  File "/home/waf/.local/lib/python3.11/site-packages/survey/_core/_io_os.py", line 119, in _recv
    text = self._i.read1()
           ^^^^^^^^^^^^^^^
KeyboardInterrupt

waf@la
```

**Comment by Exahilosys** [comment]
I missed that this occurs on locate, not measure, moved the io context to it. Please let me know if the issue persists.

**Comment by fawaf** [comment]
woot! seems like i don't see the issue anymore. i'll report back if i see it again.

**Comment by Exahilosys** [comment]
Reopened on accident, feel free to reopen if it comes up again!
